# algorithm configuration file:  albedo v6.3.1

# processing and attribute information
nam_proc:
    LinesBlock : 50
    Unit : 10
    LogLinFrequ : 100
    Compression : 0
    Path_tmp : 'tmp/'
    Processing_Mode : "N"
    Disposition_Flag : "O"
# scale factors for storage of quantities in integer variables
nam_scale:
    scale_par: 10000.
    scale_cov: 10000.
    scale_alb: 10000.
    scale_sig: 10000.
    par_min: -3.
    par_max: 3.
    cxx_min: 0.
    cxx_max: 3.
    cxy_min: -3.
    cxy_max: 3.
    alb_min: 0.
    alb_max: 1.
    sig_min: 0.
    sig_max: 1.
    MissingValue      : -1
    MissingValue_kcov : -32768
# parameterisation of the algorithm
nam_inv: 
    model                : 0
    model_len            : 3
    recursion            : true
    startseries          : true
    composition          : true
    bad_cma_elim         : false
    bad_cma_factor       : 10.0
    shadow_elim          : false
    shadow_factor        : 10.
    n_obs_limit          : 1
    n_slot_elim          : 1
    timescale            : 5.
    snow_flag_one        : true
    brdf_clim_activated  : false
    initial_value_brdf_age: -1
    initial_value_brdf_ck: .nan
    initial_value_brdf_k: .nan
    initial_value_brdf_quality: 0
    time_span_for_composition: {days: 1}
    k_reg : [0.0,   0.03,  0.3,
             0.0,   0.03,  0.3,
              0.0,   0.03,  0.3]
    sig_k_reg : [10.,   0.05,  0.5,
                 10.,   0.05,  0.5,
                 10.,   0.05,  0.5]
    sig_nadir_a: [0.001, 0.005, 0.000]
    sig_nadir_b: [0.07,  0.02,  0.04]
    sigrefl_min: 0.005
    sigrefl_max: 0.05
    sigma_co: 0.01
    co_bb_dh: [0.004724, 0.5370, 0.2805, 0.1297]
    co_vi_dh: [0.009283, 0.9606, 0.0497,-0.1245]
    co_ni_dh: [-0.000426, 0.1170, 0.5100, 0.3971]
    co_bb_dh_snow: [0.0175  , 0.3890, 0.3989,-0.0141]
    co_vi_dh_snow: [0.0155  , 0.7536, 0.2596,-0.5349]
    co_ni_dh_snow: [0.0189  , 0.0942, 0.5090, 0.4413]
    co_bb_bh: [0.004724, 0.5370, 0.2805, 0.1297]
    co_vi_bh: [0.009283, 0.9606, 0.0497,-0.1245]
    co_ni_bh: [-0.000426, 0.1170, 0.5100, 0.3971]
    co_bb_bh_snow: [0.0175  , 0.3890, 0.3989,-0.0141]
    co_vi_bh_snow: [0.0155  , 0.7536, 0.2596,-0.5349]
    co_ni_bh_snow: [0.0189  , 0.0942, 0.5090, 0.4413]
output_channel_names: [B0, B2, B3, MIR]

spectral:
  MTG:
    enable_normalisation: false
    nbands: 3
    normalisation: 
        - - - [0.0105, 0.078093, -0.037117, 0.0]
            - [0.9301, -0.2552, -0.1552, 0.0]
            - [0.0, 0.0, 0.0, 0.0]
            - [0.0, 0.0, 0.0, 0.0]
          - - [-0.001, 0.057980, -0.019530, 0.0]
            - [0.0, 0.0, 0.0, 0.0]
            - [0.9438, 0.6705, -1.8327, 1.6389]
            - [0.0, 0.0, 0.0, 0.0]
          - - [0.0066, 0.060770, -0.016470, 0.0]
            - [0.0, 0.0, 0.0, 0.0]
            - [0.0, 0.0, 0.0, 0.0]
            - [0.9982, -0.1284, 0.2834, -0.1784]
        - - - [0.0155, 0.0, 0.0, 0.0]
            - [0.128, 0.0, 0.0, 0.0]
            - [0.6395, 0.0, 0.0, 0.0]
            - [0.2505, 0.0, 0.0, 0.0]
          - - [0.0161, 0.0, 0.0, 0.0]
            - [0.1138, 0.0, 0.0, 0.0]
            - [0.6334, 0.0, 0.0, 0.0]
            - [0.2369, 0.0, 0.0, 0.0]
          - - [0.0408, 0.0, 0.0, 0.0]
            - [0.024, 0.0, 0.0, 0.0]
            - [0.123, 0.0, 0.0, 0.0]
            - [0.7794, 0.0, 0.0, 0.0]
    normalisation_err: [0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0,
      0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0]
    theta_ref_dh_limit: 85.0
    theta_sat_limit: 85.0
    theta_sat_wlimit: 85.0
    theta_sol_limit: 85.0
    theta_sol_midi_limit: 85.0
    theta_sol_wlimit: 85.0
    typical_cov_rescale:  [0.035, 0.0115, 0.012]
